# Generated by Django 3.1.5 on 2021-01-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinghome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=30)),
                ('product_img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=20)),
                ('product_type_name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.DeleteModel(
            name='Type2',
        ),
        migrations.DeleteModel(
            name='Type3',
        ),
    ]
