# Generated by Django 3.1.5 on 2021-01-28 08:56

from django.db import migrations, models
import shoppinghome.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinghome', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=shoppinghome.helpers.RandomFileName('logos')),
        ),
    ]
