# Generated by Django 3.1.5 on 2021-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinghome', '0008_auto_20210128_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type_name',
            field=models.CharField(max_length=200),
        ),
    ]
