# Generated by Django 3.1.5 on 2021-02-15 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shoppinghome', '0010_auto_20210214_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Url',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.CharField(max_length=200),
        ),
    ]
